<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <FileVersion>1.0.3</FileVersion>
    <AssemblyVersion>1.0.3</AssemblyVersion>
    <ProductVersion>1.0.3</ProductVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Classes\t4uf14p5.fd4~" />
    <None Remove="Expansion.png" />
    <None Remove="Icons\Airdrop.png" />
    <None Remove="Icons\Ambush.png" />
    <None Remove="Icons\Apple Core.png" />
    <None Remove="Icons\Apple.png" />
    <None Remove="Icons\Arrow.png" />
    <None Remove="Icons\Arrows.png" />
    <None Remove="Icons\Axe.png" />
    <None Remove="Icons\Backpack.png" />
    <None Remove="Icons\Bandage.png" />
    <None Remove="Icons\Bandit.png" />
    <None Remove="Icons\Base.png" />
    <None Remove="Icons\Batteries.png" />
    <None Remove="Icons\Bear.png" />
    <None Remove="Icons\Berries.png" />
    <None Remove="Icons\Binoculars.png" />
    <None Remove="Icons\Boat.png" />
    <None Remove="Icons\Bolt.png" />
    <None Remove="Icons\Bonfire.png" />
    <None Remove="Icons\Book-1.png" />
    <None Remove="Icons\Book-2.png" />
    <None Remove="Icons\Bottle.png" />
    <None Remove="Icons\Broken-Lighter.png" />
    <None Remove="Icons\Car.png" />
    <None Remove="Icons\Clock Blank.png" />
    <None Remove="Icons\Deliver.png" />
    <None Remove="Icons\Discord.png" />
    <None Remove="Icons\Exclamationmark.png" />
    <None Remove="Icons\Expansion BW.png" />
    <None Remove="Icons\Expansion.png" />
    <None Remove="Icons\Fireplace.png" />
    <None Remove="Icons\Fishing.png" />
    <None Remove="Icons\Forums.png" />
    <None Remove="Icons\GitHub.png" />
    <None Remove="Icons\Guilded.png" />
    <None Remove="Icons\Helicopter.png" />
    <None Remove="Icons\Home.png" />
    <None Remove="Icons\Homepage.png" />
    <None Remove="Icons\Human Skull.png" />
    <None Remove="Icons\Map Marker.png" />
    <None Remove="Icons\Mapmarker.png" />
    <None Remove="Icons\Options.png" />
    <None Remove="Icons\Patreon.png" />
    <None Remove="Icons\Paypal.png" />
    <None Remove="Icons\Questionmark.png" />
    <None Remove="Icons\Radiation.png" />
    <None Remove="Icons\Reddit.png" />
    <None Remove="Icons\Skull 1.png" />
    <None Remove="Icons\Skull 2.png" />
    <None Remove="Icons\Skull.png" />
    <None Remove="Icons\Status.png" />
    <None Remove="Icons\Steam.png" />
    <None Remove="Icons\territory.png" />
    <None Remove="Icons\Trader.png" />
    <None Remove="Icons\Twitter.png" />
    <None Remove="Icons\YouTube.png" />
    <None Remove="Images\BanditLoadout.json" />
    <None Remove="Images\EastLoadout.json" />
    <None Remove="Images\FireFighterLoadout.json" />
    <None Remove="Images\FreshSpawnLoadout.json" />
    <None Remove="Images\GorkaLoadout.json" />
    <None Remove="Images\HumanLoadout.json" />
    <None Remove="Images\NBCLoadout.json" />
    <None Remove="Images\PlayerFemaleSuitLoadout.json" />
    <None Remove="Images\PlayerMaleSuitLoadout.json" />
    <None Remove="Images\PlayerSurvivorLoadout.json" />
    <None Remove="Images\PoliceLoadout.json" />
    <None Remove="Images\SurvivorLoadout.json" />
    <None Remove="Images\TTSKOLoadout.json" />
    <None Remove="Images\WestLoadout.json" />
    <None Remove="Images\YeetBrigadeLoadout.json" />
    <None Remove="Images\YellowKingLoadout.json" />
    <None Remove="Loadouts\Civilian\biker.json" />
    <None Remove="Loadouts\Civilian\civilian.json" />
    <None Remove="Loadouts\Civilian\farmer.json" />
    <None Remove="Loadouts\Civilian\fisherman.json" />
    <None Remove="Loadouts\Civilian\freshie.json" />
    <None Remove="Loadouts\Civilian\hunter.json" />
    <None Remove="Loadouts\Civilian\lumberjack.json" />
    <None Remove="Loadouts\Civilian\suit.json" />
    <None Remove="Loadouts\Default\BanditLoadout.json" />
    <None Remove="Loadouts\Default\EastLoadout.json" />
    <None Remove="Loadouts\Default\Example.json" />
    <None Remove="Loadouts\Default\FireFighterLoadout.json" />
    <None Remove="Loadouts\Default\FreshSpawnLoadout.json" />
    <None Remove="Loadouts\Default\GorkaLoadout.json" />
    <None Remove="Loadouts\Default\HumanLoadout.json" />
    <None Remove="Loadouts\Default\NBCLoadout.json" />
    <None Remove="Loadouts\Default\PlayerFemaleSuitLoadout.json" />
    <None Remove="Loadouts\Default\PlayerMaleSuitLoadout.json" />
    <None Remove="Loadouts\Default\PlayerSurvivorLoadout.json" />
    <None Remove="Loadouts\Default\PoliceLoadout.json" />
    <None Remove="Loadouts\Default\SurvivorLoadout.json" />
    <None Remove="Loadouts\Default\TTSKOLoadout.json" />
    <None Remove="Loadouts\Default\WestLoadout.json" />
    <None Remove="Loadouts\Default\YeetBrigadeLoadout.json" />
    <None Remove="Loadouts\Default\YellowKingLoadout.json" />
    <None Remove="Loadouts\Military\CUU.json" />
    <None Remove="Loadouts\Military\Ghillie.json" />
    <None Remove="Loadouts\Military\Gorka.json" />
    <None Remove="Loadouts\Military\Nato.json" />
    <None Remove="Loadouts\Military\OMK.json" />
    <None Remove="Loadouts\Military\Pilot.json" />
    <None Remove="Loadouts\Military\Sniper.json" />
    <None Remove="Loadouts\Military\TTSKO.json" />
    <None Remove="Loadouts\Military\USMC.json" />
    <None Remove="Loadouts\Public_Services\Construction-Worker.json" />
    <None Remove="Loadouts\Public_Services\Firefighter.json" />
    <None Remove="Loadouts\Public_Services\Mechanic.json" />
    <None Remove="Loadouts\Public_Services\Medic.json" />
    <None Remove="Loadouts\Public_Services\NBC.json" />
    <None Remove="Loadouts\Public_Services\Nurse.json" />
    <None Remove="Loadouts\Public_Services\Paramedic.json" />
    <None Remove="Loadouts\Public_Services\Police.json" />
    <None Remove="Loadouts\Special\Bandit.json" />
    <None Remove="Loadouts\Special\Cowboy.json" />
    <None Remove="Loadouts\Special\Medieval.json" />
    <None Remove="Loadouts\Special\Prisoner.json" />
    <None Remove="Loadouts\Special\Spec-Ops.json" />
    <None Remove="Loadouts\Special\Survivalist.json" />
    <None Remove="Loadouts\Special\Witch.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Expansion.png" />
    <EmbeddedResource Include="Images\market_background.png" />
    <EmbeddedResource Include="Icons\Airdrop.png" />
    <EmbeddedResource Include="Icons\Ambush.png" />
    <EmbeddedResource Include="Icons\Animal Skull.png" />
    <EmbeddedResource Include="Icons\Apple Core.png" />
    <EmbeddedResource Include="Icons\Apple.png" />
    <EmbeddedResource Include="Icons\Arrow.png" />
    <EmbeddedResource Include="Icons\Arrows.png" />
    <EmbeddedResource Include="Icons\Axe.png" />
    <EmbeddedResource Include="Icons\Backpack.png" />
    <EmbeddedResource Include="Icons\Bandage.png" />
    <EmbeddedResource Include="Icons\Bandit.png" />
    <EmbeddedResource Include="Icons\Base.png" />
    <EmbeddedResource Include="Icons\Batteries.png" />
    <EmbeddedResource Include="Icons\Bear.png" />
    <EmbeddedResource Include="Icons\Berries.png" />
    <EmbeddedResource Include="Icons\Binoculars.png" />
    <EmbeddedResource Include="Icons\Boat.png" />
    <EmbeddedResource Include="Icons\Bolt.png" />
    <EmbeddedResource Include="Icons\Bonfire.png" />
    <EmbeddedResource Include="Icons\Book-1.png" />
    <EmbeddedResource Include="Icons\Book-2.png" />
    <EmbeddedResource Include="Icons\Bottle.png" />
    <EmbeddedResource Include="Icons\Broken-Lighter.png" />
    <EmbeddedResource Include="Icons\Car.png" />
    <EmbeddedResource Include="Icons\Clock Blank.png" />
    <EmbeddedResource Include="Icons\Deliver.png" />
    <EmbeddedResource Include="Icons\Discord.png" />
    <EmbeddedResource Include="Icons\Exclamationmark.png" />
    <EmbeddedResource Include="Icons\Expansion BW.png" />
    <EmbeddedResource Include="Icons\Expansion.png" />
    <EmbeddedResource Include="Icons\Fireplace.png" />
    <EmbeddedResource Include="Icons\Fishing.png" />
    <EmbeddedResource Include="Icons\Forums.png" />
    <EmbeddedResource Include="Icons\GitHub.png" />
    <EmbeddedResource Include="Icons\Guilded.png" />
    <EmbeddedResource Include="Icons\Helicopter.png" />
    <EmbeddedResource Include="Icons\Home.png" />
    <EmbeddedResource Include="Icons\Homepage.png" />
    <EmbeddedResource Include="Icons\Human Skull.png" />
    <EmbeddedResource Include="Icons\Map Marker.png" />
    <EmbeddedResource Include="Icons\Options.png" />
    <EmbeddedResource Include="Icons\Patreon.png" />
    <EmbeddedResource Include="Icons\PayPal.png" />
    <EmbeddedResource Include="Icons\Questionmark.png" />
    <EmbeddedResource Include="Icons\Radiation.png" />
    <EmbeddedResource Include="Icons\Reddit.png" />
    <EmbeddedResource Include="Icons\Skull 1.png" />
    <EmbeddedResource Include="Icons\Skull 2.png" />
    <EmbeddedResource Include="Icons\Skull.png" />
    <EmbeddedResource Include="Icons\Status.png" />
    <EmbeddedResource Include="Icons\Steam.png" />
    <EmbeddedResource Include="Icons\territory.png" />
    <EmbeddedResource Include="Icons\Trader.png" />
    <EmbeddedResource Include="Icons\Twitter.png" />
    <EmbeddedResource Include="Icons\YouTube.png" />
    <EmbeddedResource Include="Loadouts\Civilian\Biker.json" />
    <EmbeddedResource Include="Loadouts\Civilian\Civilian.json" />
    <EmbeddedResource Include="Loadouts\Civilian\Farmer.json" />
    <EmbeddedResource Include="Loadouts\Civilian\Fisherman.json" />
    <EmbeddedResource Include="Loadouts\Civilian\Freshie.json" />
    <EmbeddedResource Include="Loadouts\Civilian\Hunter.json" />
    <EmbeddedResource Include="Loadouts\Civilian\Lumberjack.json" />
    <EmbeddedResource Include="Loadouts\Civilian\Suit.json" />
    <EmbeddedResource Include="Loadouts\Military\CUU.json" />
    <EmbeddedResource Include="Loadouts\Military\Ghillie.json" />
    <EmbeddedResource Include="Loadouts\Military\Gorka.json" />
    <EmbeddedResource Include="Loadouts\Military\Nato.json" />
    <EmbeddedResource Include="Loadouts\Military\OMK.json" />
    <EmbeddedResource Include="Loadouts\Military\Pilot.json" />
    <EmbeddedResource Include="Loadouts\Military\Sniper.json" />
    <EmbeddedResource Include="Loadouts\Military\TTSKO.json" />
    <EmbeddedResource Include="Loadouts\Military\USMC.json" />
    <EmbeddedResource Include="Loadouts\Public_Services\Construction-Worker.json" />
    <EmbeddedResource Include="Loadouts\Public_Services\Firefighter.json" />
    <EmbeddedResource Include="Loadouts\Public_Services\Mechanic.json" />
    <EmbeddedResource Include="Loadouts\Public_Services\Medic.json" />
    <EmbeddedResource Include="Loadouts\Public_Services\NBC.json" />
    <EmbeddedResource Include="Loadouts\Public_Services\Nurse.json" />
    <EmbeddedResource Include="Loadouts\Public_Services\Paramedic.json" />
    <EmbeddedResource Include="Loadouts\Public_Services\Police.json" />
    <EmbeddedResource Include="Loadouts\Special\Bandit.json" />
    <EmbeddedResource Include="Loadouts\Special\Cowboy.json" />
    <EmbeddedResource Include="Loadouts\Special\Medieval.json" />
    <EmbeddedResource Include="Loadouts\Special\Prisoner.json" />
    <EmbeddedResource Include="Loadouts\Special\Spec-Ops.json" />
    <EmbeddedResource Include="Loadouts\Special\Survivalist.json" />
    <EmbeddedResource Include="Loadouts\Special\Witch.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Day2eEditor\Day2eEditor.csproj" />
    <ProjectReference Include="..\EconomyPlugin\EconomyPlugin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Forms\SelectCategoryFolderForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="IUIHandler\AI\AILightControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="IUIHandler\General\ExpansionGeneralGraveCrossControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="IUIHandler\Market\ExpansionMarketTraderItemControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="IUIHandler\Missions\ExpansionMissionEventContaminatedAreaDataControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="IUIHandler\Missions\ExpansionMissionEventContaminatedAreaPlayerDataControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="IUIHandler\Missions\ExpansionMissionEffectAreaControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="IUIHandler\P2PMarket\ExpasnionP2PMarksetTraderSpawnInfoControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="IUIHandler\PersonalStorage\ExpansionPersonalStorageSettingsCatControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="IUIHandler\PersonalStorage\ExpansionPersonalStorageSettingsGeneralControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="IUIHandler\PersonalStorage\ExpasnionPersonalStorageContainerSpawnInfoControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="IUIHandler\SafeZone\ExpansionSafeZoneCylinderControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="IUIHandler\Shared\Vector3Control.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Loadouts\Default\BanditLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\EastLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\Example.json" />
    <EmbeddedResource Include="Loadouts\Default\FireFighterLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\FreshSpawnLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\GorkaLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\HumanLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\NBCLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\PlayerFemaleSuitLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\PlayerMaleSuitLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\PlayerSurvivorLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\PoliceLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\SurvivorLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\TTSKOLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\WestLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\YeetBrigadeLoadout.json" />
    <EmbeddedResource Include="Loadouts\Default\YellowKingLoadout.json" />
  </ItemGroup>

  <Target Name="copyToPluginsFolder" AfterTargets="Build">
    <MakeDir Directories="$(SolutionDir)Day2eEditor\bin\$(Configuration)\net9.0-windows7.0\Plugins" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SolutionDir)Day2eEditor\bin\$(Configuration)\net9.0-windows7.0\Plugins" SkipUnchangedFiles="true" />
  </Target>

</Project>